/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'music' : null } |
  { 'other' : null } |
  { 'news' : null } |
  { 'education' : null } |
  { 'gaming' : null } |
  { 'sports' : null } |
  { 'comedy' : null };
export interface Channel {
  'id' : ChannelId,
  'videoCount' : bigint,
  'name' : string,
  'description' : string,
  'creationTime' : Time,
  'subscriberCount' : bigint,
}
export type ChannelId = Principal;
export interface Comment {
  'id' : CommentId,
  'text' : string,
  'author' : Principal,
  'likes' : bigint,
  'timestamp' : Time,
  'videoId' : VideoId,
}
export type CommentId = bigint;
export type ExternalBlob = Uint8Array;
export type Time = bigint;
export interface UserProfile {
  'bio' : string,
  'name' : string,
  'banner' : ExternalBlob,
  'avatar' : ExternalBlob,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Video {
  'id' : VideoId,
  'title' : string,
  'creator' : ChannelId,
  'isShort' : boolean,
  'thumbnail' : ExternalBlob,
  'views' : bigint,
  'watchTime' : bigint,
  'tags' : Array<string>,
  'description' : string,
  'videoFile' : ExternalBlob,
  'likes' : bigint,
  'category' : Category,
  'dislikes' : bigint,
  'uploadTime' : Time,
}
export type VideoId = string;
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addComment' : ActorMethod<[VideoId, string], CommentId>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createChannel' : ActorMethod<[string, string], ChannelId>,
  'getAllChannels' : ActorMethod<[], Array<Channel>>,
  'getAllVideos' : ActorMethod<[], Array<Video>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCommentsByVideoId' : ActorMethod<[VideoId], Array<Comment>>,
  'getMyChannel' : ActorMethod<[], [] | [Channel]>,
  'getMyVideos' : ActorMethod<[], Array<Video>>,
  'getSubscribers' : ActorMethod<[ChannelId], Array<Principal>>,
  'getSubscriptionCount' : ActorMethod<[ChannelId], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVideoById' : ActorMethod<[VideoId], [] | [Video]>,
  'incrementViews' : ActorMethod<[VideoId], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'likeDislikeVideo' : ActorMethod<[VideoId, boolean], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'subscribe' : ActorMethod<[ChannelId], undefined>,
  'unsubscribe' : ActorMethod<[ChannelId], undefined>,
  'updateMyChannel' : ActorMethod<[string, string], undefined>,
  'uploadVideo' : ActorMethod<
    [
      string,
      string,
      Array<string>,
      Category,
      ExternalBlob,
      ExternalBlob,
      boolean,
    ],
    VideoId
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];