/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const VideoId = IDL.Text;
export const CommentId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ChannelId = IDL.Principal;
export const Time = IDL.Int;
export const Channel = IDL.Record({
  'id' : ChannelId,
  'videoCount' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'creationTime' : Time,
  'subscriberCount' : IDL.Nat,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Category = IDL.Variant({
  'music' : IDL.Null,
  'other' : IDL.Null,
  'news' : IDL.Null,
  'education' : IDL.Null,
  'gaming' : IDL.Null,
  'sports' : IDL.Null,
  'comedy' : IDL.Null,
});
export const Video = IDL.Record({
  'id' : VideoId,
  'title' : IDL.Text,
  'creator' : ChannelId,
  'isShort' : IDL.Bool,
  'thumbnail' : ExternalBlob,
  'views' : IDL.Nat,
  'watchTime' : IDL.Nat,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'videoFile' : ExternalBlob,
  'likes' : IDL.Nat,
  'category' : Category,
  'dislikes' : IDL.Nat,
  'uploadTime' : Time,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'name' : IDL.Text,
  'banner' : ExternalBlob,
  'avatar' : ExternalBlob,
});
export const Comment = IDL.Record({
  'id' : CommentId,
  'text' : IDL.Text,
  'author' : IDL.Principal,
  'likes' : IDL.Nat,
  'timestamp' : Time,
  'videoId' : VideoId,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addComment' : IDL.Func([VideoId, IDL.Text], [CommentId], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createChannel' : IDL.Func([IDL.Text, IDL.Text], [ChannelId], []),
  'getAllChannels' : IDL.Func([], [IDL.Vec(Channel)], ['query']),
  'getAllVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCommentsByVideoId' : IDL.Func([VideoId], [IDL.Vec(Comment)], ['query']),
  'getMyChannel' : IDL.Func([], [IDL.Opt(Channel)], ['query']),
  'getMyVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
  'getSubscribers' : IDL.Func([ChannelId], [IDL.Vec(IDL.Principal)], ['query']),
  'getSubscriptionCount' : IDL.Func([ChannelId], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVideoById' : IDL.Func([VideoId], [IDL.Opt(Video)], ['query']),
  'incrementViews' : IDL.Func([VideoId], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'likeDislikeVideo' : IDL.Func([VideoId, IDL.Bool], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'subscribe' : IDL.Func([ChannelId], [], []),
  'unsubscribe' : IDL.Func([ChannelId], [], []),
  'updateMyChannel' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'uploadVideo' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        Category,
        ExternalBlob,
        ExternalBlob,
        IDL.Bool,
      ],
      [VideoId],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const VideoId = IDL.Text;
  const CommentId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ChannelId = IDL.Principal;
  const Time = IDL.Int;
  const Channel = IDL.Record({
    'id' : ChannelId,
    'videoCount' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'creationTime' : Time,
    'subscriberCount' : IDL.Nat,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Category = IDL.Variant({
    'music' : IDL.Null,
    'other' : IDL.Null,
    'news' : IDL.Null,
    'education' : IDL.Null,
    'gaming' : IDL.Null,
    'sports' : IDL.Null,
    'comedy' : IDL.Null,
  });
  const Video = IDL.Record({
    'id' : VideoId,
    'title' : IDL.Text,
    'creator' : ChannelId,
    'isShort' : IDL.Bool,
    'thumbnail' : ExternalBlob,
    'views' : IDL.Nat,
    'watchTime' : IDL.Nat,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'videoFile' : ExternalBlob,
    'likes' : IDL.Nat,
    'category' : Category,
    'dislikes' : IDL.Nat,
    'uploadTime' : Time,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'name' : IDL.Text,
    'banner' : ExternalBlob,
    'avatar' : ExternalBlob,
  });
  const Comment = IDL.Record({
    'id' : CommentId,
    'text' : IDL.Text,
    'author' : IDL.Principal,
    'likes' : IDL.Nat,
    'timestamp' : Time,
    'videoId' : VideoId,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addComment' : IDL.Func([VideoId, IDL.Text], [CommentId], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createChannel' : IDL.Func([IDL.Text, IDL.Text], [ChannelId], []),
    'getAllChannels' : IDL.Func([], [IDL.Vec(Channel)], ['query']),
    'getAllVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCommentsByVideoId' : IDL.Func([VideoId], [IDL.Vec(Comment)], ['query']),
    'getMyChannel' : IDL.Func([], [IDL.Opt(Channel)], ['query']),
    'getMyVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
    'getSubscribers' : IDL.Func(
        [ChannelId],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getSubscriptionCount' : IDL.Func([ChannelId], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVideoById' : IDL.Func([VideoId], [IDL.Opt(Video)], ['query']),
    'incrementViews' : IDL.Func([VideoId], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'likeDislikeVideo' : IDL.Func([VideoId, IDL.Bool], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'subscribe' : IDL.Func([ChannelId], [], []),
    'unsubscribe' : IDL.Func([ChannelId], [], []),
    'updateMyChannel' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'uploadVideo' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          Category,
          ExternalBlob,
          ExternalBlob,
          IDL.Bool,
        ],
        [VideoId],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };